# Generated by Django 4.2.16 on 2024-10-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("froide_fax", "0002_auto_20180719_1235"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaxPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (("can_always_fax", "Can always send fax messages"),),
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
